/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SettingLayoutRouteImport } from './routes/_settingLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingLayoutSettingsIndexRouteImport } from './routes/_settingLayout.settings.index'
import { Route as SettingLayoutSettingsProfileRouteImport } from './routes/_settingLayout.settings.profile'
import { Route as SettingLayoutSettingsLoginRouteImport } from './routes/_settingLayout.settings.login'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingLayoutRoute = SettingLayoutRouteImport.update({
  id: '/_settingLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingLayoutSettingsIndexRoute =
  SettingLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => SettingLayoutRoute,
  } as any)
const SettingLayoutSettingsProfileRoute =
  SettingLayoutSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => SettingLayoutRoute,
  } as any)
const SettingLayoutSettingsLoginRoute =
  SettingLayoutSettingsLoginRouteImport.update({
    id: '/settings/login',
    path: '/settings/login',
    getParentRoute: () => SettingLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings/login': typeof SettingLayoutSettingsLoginRoute
  '/settings/profile': typeof SettingLayoutSettingsProfileRoute
  '/settings/': typeof SettingLayoutSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings/login': typeof SettingLayoutSettingsLoginRoute
  '/settings/profile': typeof SettingLayoutSettingsProfileRoute
  '/settings': typeof SettingLayoutSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_settingLayout': typeof SettingLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/_settingLayout/settings/login': typeof SettingLayoutSettingsLoginRoute
  '/_settingLayout/settings/profile': typeof SettingLayoutSettingsProfileRoute
  '/_settingLayout/settings/': typeof SettingLayoutSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/settings/login'
    | '/settings/profile'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/settings/login' | '/settings/profile' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_settingLayout'
    | '/about'
    | '/_settingLayout/settings/login'
    | '/_settingLayout/settings/profile'
    | '/_settingLayout/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingLayoutRoute: typeof SettingLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settingLayout': {
      id: '/_settingLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SettingLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settingLayout/settings/': {
      id: '/_settingLayout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingLayoutSettingsIndexRouteImport
      parentRoute: typeof SettingLayoutRoute
    }
    '/_settingLayout/settings/profile': {
      id: '/_settingLayout/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingLayoutSettingsProfileRouteImport
      parentRoute: typeof SettingLayoutRoute
    }
    '/_settingLayout/settings/login': {
      id: '/_settingLayout/settings/login'
      path: '/settings/login'
      fullPath: '/settings/login'
      preLoaderRoute: typeof SettingLayoutSettingsLoginRouteImport
      parentRoute: typeof SettingLayoutRoute
    }
  }
}

interface SettingLayoutRouteChildren {
  SettingLayoutSettingsLoginRoute: typeof SettingLayoutSettingsLoginRoute
  SettingLayoutSettingsProfileRoute: typeof SettingLayoutSettingsProfileRoute
  SettingLayoutSettingsIndexRoute: typeof SettingLayoutSettingsIndexRoute
}

const SettingLayoutRouteChildren: SettingLayoutRouteChildren = {
  SettingLayoutSettingsLoginRoute: SettingLayoutSettingsLoginRoute,
  SettingLayoutSettingsProfileRoute: SettingLayoutSettingsProfileRoute,
  SettingLayoutSettingsIndexRoute: SettingLayoutSettingsIndexRoute,
}

const SettingLayoutRouteWithChildren = SettingLayoutRoute._addFileChildren(
  SettingLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingLayoutRoute: SettingLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
