/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SettingsLayoutRouteImport } from './routes/_settingsLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsPasswordRouteImport } from './routes/settings.password'
import { Route as SettingsLayoutSettingsIndexRouteImport } from './routes/_settingsLayout.settings.index'
import { Route as SettingsLayoutSettingsProfileRouteImport } from './routes/_settingsLayout.settings.profile'
import { Route as SettingsLayoutSettingsPaymentRouteImport } from './routes/_settingsLayout.settings.payment'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLayoutRoute = SettingsLayoutRouteImport.update({
  id: '/_settingsLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPasswordRoute = SettingsPasswordRouteImport.update({
  id: '/settings/password',
  path: '/settings/password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLayoutSettingsIndexRoute =
  SettingsLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => SettingsLayoutRoute,
  } as any)
const SettingsLayoutSettingsProfileRoute =
  SettingsLayoutSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => SettingsLayoutRoute,
  } as any)
const SettingsLayoutSettingsPaymentRoute =
  SettingsLayoutSettingsPaymentRouteImport.update({
    id: '/settings/payment',
    path: '/settings/payment',
    getParentRoute: () => SettingsLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/payment': typeof SettingsLayoutSettingsPaymentRoute
  '/settings/profile': typeof SettingsLayoutSettingsProfileRoute
  '/settings/': typeof SettingsLayoutSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/payment': typeof SettingsLayoutSettingsPaymentRoute
  '/settings/profile': typeof SettingsLayoutSettingsProfileRoute
  '/settings': typeof SettingsLayoutSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_settingsLayout': typeof SettingsLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/_settingsLayout/settings/payment': typeof SettingsLayoutSettingsPaymentRoute
  '/_settingsLayout/settings/profile': typeof SettingsLayoutSettingsProfileRoute
  '/_settingsLayout/settings/': typeof SettingsLayoutSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/settings/password'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/settings/password'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_settingsLayout'
    | '/about'
    | '/settings/password'
    | '/_settingsLayout/settings/payment'
    | '/_settingsLayout/settings/profile'
    | '/_settingsLayout/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsLayoutRoute: typeof SettingsLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  SettingsPasswordRoute: typeof SettingsPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settingsLayout': {
      id: '/_settingsLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SettingsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/password': {
      id: '/settings/password'
      path: '/settings/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof SettingsPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settingsLayout/settings/': {
      id: '/_settingsLayout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsLayoutSettingsIndexRouteImport
      parentRoute: typeof SettingsLayoutRoute
    }
    '/_settingsLayout/settings/profile': {
      id: '/_settingsLayout/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsLayoutSettingsProfileRouteImport
      parentRoute: typeof SettingsLayoutRoute
    }
    '/_settingsLayout/settings/payment': {
      id: '/_settingsLayout/settings/payment'
      path: '/settings/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof SettingsLayoutSettingsPaymentRouteImport
      parentRoute: typeof SettingsLayoutRoute
    }
  }
}

interface SettingsLayoutRouteChildren {
  SettingsLayoutSettingsPaymentRoute: typeof SettingsLayoutSettingsPaymentRoute
  SettingsLayoutSettingsProfileRoute: typeof SettingsLayoutSettingsProfileRoute
  SettingsLayoutSettingsIndexRoute: typeof SettingsLayoutSettingsIndexRoute
}

const SettingsLayoutRouteChildren: SettingsLayoutRouteChildren = {
  SettingsLayoutSettingsPaymentRoute: SettingsLayoutSettingsPaymentRoute,
  SettingsLayoutSettingsProfileRoute: SettingsLayoutSettingsProfileRoute,
  SettingsLayoutSettingsIndexRoute: SettingsLayoutSettingsIndexRoute,
}

const SettingsLayoutRouteWithChildren = SettingsLayoutRoute._addFileChildren(
  SettingsLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsLayoutRoute: SettingsLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  SettingsPasswordRoute: SettingsPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
